---
- name: Create the gatekeeper user
  tags: [gatekeeper]
  user:
    name: '{{ ubuntu_secure_gatekeeper_name }}'
    state: present
    password: '{{ ubuntu_secure_gatekeeper_password }}'
    groups: sudo
    shell: /bin/bash
    comment: The Almighty Gatekeeper

- include: includes/_authorized_key.yml keyfile_path={{ item }}
  with_items: '{{ ubuntu_secure_gatekeeper_public_keys }}'

- name: Upload custom dotfiles to gatekeeper's and root's home
  tags: [gatekeeper]
  copy:
    src: home/
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.owner }}'
    mode: 0600
  with_items:
    - dest: '/home/{{ ubuntu_secure_gatekeeper_name }}'
      owner: '{{ ubuntu_secure_gatekeeper_name }}'
    - dest: /root
      owner: root

- name: Upload custom sshd config
  tags: [gatekeeper]
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify:
    - Restart SSH
