---
- name: Create the gatekeeper user
  tags: [gatekeeper]
  user:
    name: '{{ ubuntu_secure_gatekeeper_name }}'
    state: present
    password: '{{ ubuntu_secure_gatekeeper_password }}'
    groups: sudo
    shell: /bin/bash
    comment: The Almighty Gatekeeper

- name: Add authorized SSH public keys for the gatekeeper
  tags: [gatekeeper]
  authorized_key:
    user: '{{ ubuntu_secure_gatekeeper_name }}'
    key: "{{ lookup('file', item) }}"
    state: present
  with_items: ubuntu_secure_gatekeeper_public_keys

- name: Upload custom dotfiles to gatekeeper's home
  tags: [gatekeeper]
  copy:
    src: home/gatekeeper/
    dest: '/home/{{ ubuntu_secure_gatekeeper_name }}'
    owner: '{{ ubuntu_secure_gatekeeper_name }}'
    group: '{{ ubuntu_secure_gatekeeper_name }}'

- name: Upload custom sshd config
  tags: [gatekeeper]
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
