#!/usr/bin/env bash

# Reset tables and chains
iptables           -F
iptables           -X
iptables -t nat    -F
iptables -t nat    -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw    -F
iptables -t raw    -X

# Set DROP as global default policy
iptables -P INPUT   DROP
iptables -P FORWARD DROP
iptables -P OUTPUT  DROP

# Drop invalid requests
iptables -A INPUT -m state --state INVALID -j DROP

# Drop bogon sources
iptables -A INPUT -s 0.0.0.0/8       -j DROP
iptables -A INPUT -s 10.0.0.0/8      -j DROP
iptables -A INPUT -s 100.64.0.0/10   -j DROP
iptables -A INPUT -s 127.0.0.0/8     -j DROP
iptables -A INPUT -s 169.254.0.0/16  -j DROP
iptables -A INPUT -s 172.16.0.0/12   -j DROP
iptables -A INPUT -s 192.0.0.0/24    -j DROP
iptables -A INPUT -s 192.0.2.0/24    -j DROP
iptables -A INPUT -s 192.168.0.0/16  -j DROP
iptables -A INPUT -s 198.18.0.0/15   -j DROP
iptables -A INPUT -s 198.51.100.0/24 -j DROP
iptables -A INPUT -s 203.0.113.0/24  -j DROP
iptables -A INPUT -s 224.0.0.0/4     -j DROP
iptables -A INPUT -s 240.0.0.0/4     -j DROP

# Accept (throttled) ICMP requests
iptables -N PING_FLOOD_FILTER
iptables -A INPUT -p icmp --icmp-type echo-request -j PING_FLOOD_FILTER
iptables -A PING_FLOOD_FILTER -m hashlimit --hashlimit-name PING_FLOOD --hashlimit-above 1/second --hashlimit-burst 1 -j REJECT --reject-with icmp-admin-prohibited
iptables -A PING_FLOOD_FILTER -j ACCEPT

# Drop invalid TCP packets
iptables -A INPUT -p tcp --tcp-flags ALL ALL  -j DROP # XMAS
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP # NULL
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP

# TCP basic flood protection
iptables -A INPUT -p tcp -m connlimit --connlimit-above 20 -j DROP
iptables -A INPUT -p tcp --syn -m recent --name SYN_FLOOD --set
iptables -A INPUT -p tcp --syn -m recent --name SYN_FLOOD --rcheck --rttl --seconds 1 --hitcount 11 -j DROP

# UDP basic flood protection
iptables -N UDP_INPUT_FLOOD_FILTER
iptables -N UDP_OUTPUT_FLOOD_FILTER
iptables -A INPUT  -p udp -j UDP_INPUT_FLOOD_FILTER
iptables -A OUTPUT -p udp -j UDP_OUTPUT_FLOOD_FILTER
iptables -A UDP_INPUT_FLOOD_FILTER  -m limit --limit 10/second  -j RETURN
iptables -A UDP_OUTPUT_FLOOD_FILTER -m limit --limit 100/second -j RETURN
iptables -A UDP_INPUT_FLOOD_FILTER  -j DROP
iptables -A UDP_OUTPUT_FLOOD_FILTER -j DROP

# Accept related, established and local requests
iptables -A INPUT  -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT  -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Authorized INPUT requests
iptables -A INPUT -p tcp --dport {{ sshd_port }} -j ACCEPT # SSH
iptables -A INPUT -p udp --dport 123             -j ACCEPT # NTP

# Authorized OUTPUT requests
iptables -A OUTPUT -p tcp --dport 22   -j ACCEPT # SSH
iptables -A OUTPUT -p tcp --dport 25   -j ACCEPT # SMTP
iptables -A OUTPUT -p tcp --dport 53   -j ACCEPT # DNS (TCP)
iptables -A OUTPUT -p udp --dport 53   -j ACCEPT # DNS (UDP)
iptables -A OUTPUT -p udp --dport 67   -j ACCEPT # DHCP/BOOTP
iptables -A OUTPUT -p tcp --dport 80   -j ACCEPT # HTTP
iptables -A OUTPUT -p udp --dport 123  -j ACCEPT # NTP
iptables -A OUTPUT -p tcp --dport 443  -j ACCEPT # HTTPS
iptables -A OUTPUT -p tcp --dport 465  -j ACCEPT # SMTP (secure)
iptables -A OUTPUT -p tcp --dport 587  -j ACCEPT # SMTP (submission)
iptables -A OUTPUT -p tcp --dport 953  -j ACCEPT # rDNS (TCP)
iptables -A OUTPUT -p udp --dport 953  -j ACCEPT # rDNS (UDP)
iptables -A OUTPUT -p udp --dport 5353 -j ACCEPT # mDNS

{{ iptables_additional_rules }}

# Exit cleanly, or the server will hang during booting
exit 0
