---
- name: Update GRUB
  shell: 'update-grub2 || update-grub'

- name: Restart networking
  shell: 'ifdown --exclude=lo --all && sleep 1 && ifup --exclude=lo --all'

- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Reboot server
  shell: 'sleep 2 && reboot'
  async: 1
  poll: 0
  ignore_errors: true
