---
- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Restart networking
  service:
    name: networking
    state: restarted

- name: Restart network interfaces
  shell: 'ifdown {{ item }} && ifup {{ item }}'
  with_items: ansible_interfaces
  when: item|match('^eth\d+$')
