---
- name: Check if local public key file exists
  tags: [gatekeeper]
  stat:
    path: '{{ keyfile_path }}'
  register: keyfile_stat

- name: Add authorized SSH public key for the gatekeeper
  tags: [gatekeeper]
  authorized_key:
    user: '{{ ubuntu_secure_gatekeeper_name }}'
    key: "{{ lookup('file', keyfile_path) }}"
    state: present
  when: keyfile_stat.stat.exists
