#!/bin/sh

# Reset tables and chains
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X

# Set DROP as global default policy
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

# Drop invalid requests
iptables -A INPUT -m state --state INVALID -j DROP

# Drop invalid TCP packets
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP # XMAS
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP # NULL
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP

# Accept related, established and local requests
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Accept (throttled) ping requests
iptables -N PING_FLOOD_FILTER
iptables -A INPUT -p icmp --icmp-type echo-request -j PING_FLOOD_FILTER
iptables -A PING_FLOOD_FILTER -m hashlimit --hashlimit-name PING_FLOOD --hashlimit-mode srcip --hashlimit-above 1/second --hashlimit-burst 2 -j REJECT --reject-with icmp-admin-prohibited
iptables -A PING_FLOOD_FILTER -j ACCEPT

# Basic TCP flood protection
iptables -A INPUT -p tcp -m connlimit --connlimit-above 20 -j DROP
iptables -N SYN_FLOOD_FILTER
iptables -A INPUT -p tcp --syn -j SYN_FLOOD_FILTER
iptables -A SYN_FLOOD_FILTER -m hashlimit --hashlimit-name SYN_FLOOD --hashlimit-mode srcip --hashlimit-above 5/second -j DROP

# Basic UDP flood protection
iptables -A INPUT -m hashlimit --hashlimit-name UDP_INPUT_FLOOD --hashlimit-above 20/second -j DROP
iptables -A OUTPUT -m hashlimit --hashlimit-name UDP_OUTPUT_FLOOD --hashlimit-above 200/second --hashlimit-burst 10 -j DROP

# Authorized INPUT requests
iptables -A INPUT -p tcp --dport {{ ssh_alternate_port }} -j ACCEPT # SSH

# Authorized OUTPUT requests
iptables -A OUTPUT -p icmp -j ACCEPT # ICMP
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT # SSH
iptables -A OUTPUT -p tcp --dport 25 -j ACCEPT # SMTP
iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT # DNS (TCP)
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT # DNS (UDP)
iptables -A OUTPUT -p udp --dport 67 -j ACCEPT # DHCP/BOOTP
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT # HTTP
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT # NTP
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT # HTTPS
iptables -A OUTPUT -p tcp --dport 465 -j ACCEPT # SMTP (secure)
iptables -A OUTPUT -p tcp --dport 587 -j ACCEPT # SMTP (submission)
iptables -A OUTPUT -p tcp --dport 953 -j ACCEPT # rDNS (TCP)
iptables -A OUTPUT -p udp --dport 953 -j ACCEPT # rDNS (UDP)
iptables -A OUTPUT -p udp --dport 5353 -j ACCEPT # mDNS

# Additional user-defined rules
{{ iptables_additional_rules }}

# Exit cleanly, or the server will hang during booting
exit 0
